# Generated by Django 5.2 on 2025-04-24 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('To-do', 'To-do'), ('In-progress', 'In-progress'), ('In-review', 'In-review'), ('Done', 'Done')], default='To-do', max_length=20),
        ),
    ]
